// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Attachment struct {
	EntryID   int64
	StoryID   int64
	Source    string
	CreatedAt string
}

type Entry struct {
	ID           int64
	FeedID       int64
	Guid         *string
	CanonicalUrl string
	Title        string
	Body         string
	PublishedAt  *string
	ContentHash  string
	NotePath     string
	CreatedAt    string
}

type Feed struct {
	ID                  int64
	Url                 string
	Title               string
	Active              bool
	CreatedAt           string
	LastFetchedAt       *string
	ConsecutiveFailures int64
	LastError           string
}

type Story struct {
	ID        int64
	Name      string
	Status    string
	CreatedAt string
	ClosedAt  *string
}
