// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
    feed_id, guid, canonical_url, title, body, published_at, content_hash, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, feed_id, guid, canonical_url, title, body, published_at, content_hash, note_path, created_at
`

type CreateEntryParams struct {
	FeedID       int64
	Guid         *string
	CanonicalUrl string
	Title        string
	Body         string
	PublishedAt  *string
	ContentHash  string
	CreatedAt    string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.FeedID,
		arg.Guid,
		arg.CanonicalUrl,
		arg.Title,
		arg.Body,
		arg.PublishedAt,
		arg.ContentHash,
		arg.CreatedAt,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.CanonicalUrl,
		&i.Title,
		&i.Body,
		&i.PublishedAt,
		&i.ContentHash,
		&i.NotePath,
		&i.CreatedAt,
	)
	return i, err
}

const createFeed = `-- name: CreateFeed :one

INSERT INTO feeds (url, title, created_at)
VALUES (?, ?, ?)
RETURNING id, url, title, active, created_at, last_fetched_at, consecutive_failures, last_error
`

type CreateFeedParams struct {
	Url       string
	Title     string
	CreatedAt string
}

// Named queries for sqlc. Each `-- name: X :kind` comment tells sqlc what Go
// method to generate and what it returns: :one (single row), :many (slice),
// :exec (no rows, just error). The `?` placeholders bind in argument order.
//
// This first slice covers feeds (milestone 3, Feed CRUD) and the two entry
// queries the fetcher will need (milestone 5). Story/attachment queries arrive
// with their own milestone.
func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.Url, arg.Title, arg.CreatedAt)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Active,
		&i.CreatedAt,
		&i.LastFetchedAt,
		&i.ConsecutiveFailures,
		&i.LastError,
	)
	return i, err
}

const createFeedIfNew = `-- name: CreateFeedIfNew :execrows
INSERT INTO feeds (url, title, created_at)
VALUES (?, ?, ?)
ON CONFLICT (url) DO NOTHING
`

type CreateFeedIfNewParams struct {
	Url       string
	Title     string
	CreatedAt string
}

// Idempotent insert for bulk import: ON CONFLICT does nothing when the url
// already exists. :execrows returns the rows-affected count (1 = inserted,
// 0 = already present), so the importer can tally new vs skipped.
func (q *Queries) CreateFeedIfNew(ctx context.Context, arg CreateFeedIfNewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createFeedIfNew, arg.Url, arg.Title, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds
WHERE id = ?
`

func (q *Queries) DeleteFeed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, id)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, feed_id, guid, canonical_url, title, body, published_at, content_hash, note_path, created_at FROM entries
WHERE id = ?
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.CanonicalUrl,
		&i.Title,
		&i.Body,
		&i.PublishedAt,
		&i.ContentHash,
		&i.NotePath,
		&i.CreatedAt,
	)
	return i, err
}

const getFeed = `-- name: GetFeed :one
SELECT id, url, title, active, created_at, last_fetched_at, consecutive_failures, last_error FROM feeds
WHERE id = ?
`

func (q *Queries) GetFeed(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Active,
		&i.CreatedAt,
		&i.LastFetchedAt,
		&i.ConsecutiveFailures,
		&i.LastError,
	)
	return i, err
}

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT id, url, title, active, created_at, last_fetched_at, consecutive_failures, last_error FROM feeds
WHERE url = ?
`

func (q *Queries) GetFeedByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Active,
		&i.CreatedAt,
		&i.LastFetchedAt,
		&i.ConsecutiveFailures,
		&i.LastError,
	)
	return i, err
}

const listActiveFeeds = `-- name: ListActiveFeeds :many
SELECT id, url, title, active, created_at, last_fetched_at, consecutive_failures, last_error FROM feeds
WHERE active = 1
ORDER BY id
`

func (q *Queries) ListActiveFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listActiveFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Active,
			&i.CreatedAt,
			&i.LastFetchedAt,
			&i.ConsecutiveFailures,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, url, title, active, created_at, last_fetched_at, consecutive_failures, last_error FROM feeds
ORDER BY id
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Active,
			&i.CreatedAt,
			&i.LastFetchedAt,
			&i.ConsecutiveFailures,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedActive = `-- name: SetFeedActive :exec
UPDATE feeds
SET active = ?
WHERE id = ?
`

type SetFeedActiveParams struct {
	Active bool
	ID     int64
}

func (q *Queries) SetFeedActive(ctx context.Context, arg SetFeedActiveParams) error {
	_, err := q.db.ExecContext(ctx, setFeedActive, arg.Active, arg.ID)
	return err
}
